### ISSUE TITLE
Screen sharing

### ISSUE THREAD

**Issue by rimonhanna** [Urban82/electron-google-meet#2]
Hi, I was wondering if you managed to get screen sharing to work on mac? I've tried many solutions with different approaches but it seems no matter what I do, I can't managed to get it to work. I'd really appreciate your help on this

**Comment by Urban82** [comment]
Hi, I'm sorry, but I was not able to start screen share at all, on any platform. I think is related to Electron sandbox, but I had no time to study it further.

**Comment by rimonhanna** [comment]
Ok, thanks! :)
